### ISSUE TITLE
User can place an order - Back End.

### ISSUE THREAD

**Issue by mrjamesjcho** [mrjamesjcho/lego-collector#26]
### ✅ Task List

- [ ] Create an `orders` table in the `wickedSales` database according to the provided table structure.
- [ ] Create a new file at `server/api/orders.php`
- [ ] Register a new resource in `server/public/index.php` for `/api/orders`, modify `server/api/orders.php` to print some kind of response like "Hello", and try sending a `POST` request to `localhost:9000/api/orders` to make sure that the resource is reachable.
- [ ] In `orders.php`, add a conditional statement to handle `POST` requests, as seen in `health-check.php`.
- [ ] Within the `POST` handler, check if the `$_SESSION` super global has a `'cart_id'` key. If it does not, then the client does not have an active shopping cart, and an `ApiError` should be thrown, indicating that an active shopping cart is required with a status code of `400`.
- [ ] If the client _does_ have an active shopping cart, then the `$request['body']` should be checked for the presence of `'name'`, `'creditCard'`, and `'shippingAddress'` keys. If any of them are missing, then an `ApiError` should be thrown with a status of `400`, and a message clearly communicating to the client what is wrong with their request.
- [ ] Create a SQL string to insert a `cartId`, `name`, `creditCard`, and `shippingAddress` into the `orders` table, but put `?` placeholders where the values would go.
- [ ] Create a prepared statement using the SQL string.
- [ ] Bind the `$_SESSION['cart_id']` and client-supplied order details to the prepared statement.
- [ ] Execute the prepared statement and store its `insert_id` in a variable.
- [ ] Now that the order has been placed, the client's active shopping cart should be reset by unsetting the `$_SESSION['cart_id']`.
- [ ] Assign the client-supplied data and the new order id to the `$response['body']` and `send()` the repsonse.
